version: "2"

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - "./sys/config/nginx/default.conf:/etc/nginx/sites-available/default"
      - "./sys/config/nginx/default.conf:/etc/nginx/sites-enabled/default"
      - "./www:/usr/share/nginx/html"
      - "./sys/var/log/:/var/log/nginx/"
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/sites-available/default > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
#      - db

  php:
#    image: php:7.1-fpm
    build:
      context: ./sys/config/php
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_INTL=true
        - INSTALL_IMAGE_OPTIMIZERS=true
        - INSTALL_IMAGEMAGICK=true
        - INSTALL_OPCACHE=true
        - INSTALL_MEMCACHED=false
        - INSTALL_EXIF=true
        - INSTALL_PHPREDIS=true
    container_name: php
    ports:
      - "9000:9000"
    volumes:
        - "./www:/usr/share/nginx/html"

#  db:
#
#  reverse-proxy:
#
#  redis:
#
#  mail:
#
#  log: