version: "2"

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - "./sys/config/nginx/default.conf:/etc/nginx/sites-available/default"
      - "./sys/config/nginx/default.conf:/etc/nginx/sites-enabled/default"
      - "./www:/usr/share/nginx/html"
      - "./sys/var/log/:/var/log/nginx/"
    ports:
      - "8001:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/sites-available/default > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    links:
      - php
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./sys/config/php
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - INSTALL_INTL=${INSTALL_INTL}
        - INSTALL_IMAGE_OPTIMIZERS=${INSTALL_IMAGE_OPTIMIZERS}
        - INSTALL_IMAGEMAGICK=${INSTALL_IMAGEMAGICK}
        - INSTALL_OPCACHE=${INSTALL_OPCACHE}
        - INSTALL_MEMCACHED=${INSTALL_MEMCACHED}
        - INSTALL_EXIF=${INSTALL_EXIF}
        - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
    ports:
      - "9000:9000"
    volumes:
      - "./www:/usr/share/nginx/html"
    links:
      - db
      - mail
    depends_on:
      - db
      - mail

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - "./sys/var/data/db:/var/lib/mysql"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8183:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  mail:
    container_name: mail
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  varnish:
    container_name: varnish
    image: million12/varnish
    links:
      - web:web
    volumes:
      - "./sys/config/varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - 8000:80
    links:
      - web
    depends_on:
      - web

  elk:
    container_name: elk
    image: willdurand/elk
    ports:
      - 8002:80
    volumes:
      - ./sys/config/elk/logstash:/etc/logstash
      - ./sys/config/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
      - php
      - web

#  jenkins:
#    image: jenkins/jenkins:lts
#    container_name: jenkins
##    environment:
#    ports:
#      - "8080:8080"
#      - "50000:50000"
##    volumes:
##      - "./sys/var/data/db:/var/lib/mysql"
