version: "2"

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - "./sys/config/nginx/default.conf:/etc/nginx/sites-available/default"
      - "./sys/config/nginx/default.conf:/etc/nginx/sites-enabled/default"
      - "./www:/usr/share/nginx/html"
      - "./sys/var/log/:/var/log/nginx/"
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/sites-available/default > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - db

  php:
    container_name: php
    build:
      context: ./sys/config/php
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_INTL=true
        - INSTALL_IMAGE_OPTIMIZERS=true
        - INSTALL_IMAGEMAGICK=true
        - INSTALL_OPCACHE=true
        - INSTALL_MEMCACHED=false
        - INSTALL_EXIF=true
        - INSTALL_PHPREDIS=true
    ports:
      - "9000:9000"
    volumes:
      - "./www:/usr/share/nginx/html"

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
    ports:
      - "3307:3306"
    volumes:
      - "./sys/var/data/db:/var/lib/mysql"

  elk:
    container_name: elk
    image: willdurand/elk
    ports:
      - 8001:80
    volumes:
      - ./sys/config/elk/logstash:/etc/logstash
      - ./sys/config/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
      - php
      - web

#  jenkins:
#    image: jenkins/jenkins:lts
#    container_name: jenkins
##    environment:
#    ports:
#      - "8080:8080"
#      - "50000:50000"
##    volumes:
##      - "./sys/var/data/db:/var/lib/mysql"

  ubuntu1:
    build:
      context: .
    container_name: ubuntu1
    command: /bin/bash -c "tail -f /dev/null"
    volumes:
      - "./sources.list:/etc/apt/sources.list"

  ubuntu2:
    build:
      context: .
    container_name: ubuntu2
    command: /bin/bash -c "tail -f /dev/null"
    volumes:
      - "./sources.list:/etc/apt/sources.list"
